# Generated by Django 5.0.3 on 2024-04-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField()),
                ('from_msg', models.CharField()),
                ('to_msg', models.CharField()),
                ('date_sent', models.DateTimeField()),
                ('date_received', models.DateTimeField()),
                ('subject', models.CharField()),
                ('files_enclosed', models.CharField()),
            ],
        ),
    ]
